### ISSUE TITLE
Tried your UI but can't seem to connect backend API

### ISSUE THREAD

**Issue by FlareHashr** [AlphaX-Projects/alphaxcore-WebUI#1]
First, thanks for being active with your github, I been trying for a long time to find something more updated with the miningcore pool and found your repository through Dirty Harry's git.

I am not planning to use your WebUI as is, I ended up forking it to use as a baseline to make it something more unique to our pool. So far I have the backend running with Ritocoin for testing....starts up fine there, webUI is showing with SSL but for some reason no matter what i do I can't seem to get the API to end up on the webpage.

I have tried reverse proxies like you normally have to do in nginx, also tried using nginx proxy manager as well and let that open up to websockets and added in the necessary proxy options but nothing seems to take.

I followed old trails from the miningcore git but it seems all their answers no longer work with this kind of UI you guys put together. I have changed the settings to our domain in the alphaxcore.js file, config on backend is setup right now with 127.0.0.1 and port 4000 but I did also try 0.0.0.0

http and https shows nothing if I do /api ....all ports are open on 4000 so I am kind of lost at this stage what maybe happening.

Know you guys are busy but if you have any idea where I can try something else to pull it forward it would be a huge help.

Again thanks for bringing life back to this project, I plan to expand on it myself once I get past this issue I am sure is something small I am missing

**Comment by FlareHashr** [comment]
Oh to add, i am right now testing with yours not Dirty Harry's git but same results on both versions, no API being put to the front, though its saying its open and good on the backend

**Comment by AlphaX-Projects** [comment]
You opend Port 4000 ?
and change in alphaxcore.js the api enpoint etc ?

**Comment by AlphaX-Projects** [comment]
since no answer guess is fixed
